export const AGGREGATE_COVERAGE_THRESHOLDS = {
  branches: 85,
  functions: 90,
  lines: 90,
  statements: 90,
  perFile: false
} as const

export const EXTENSION_COVERAGE_FILES = [
  'utils/number.ts',
  'utils/string.ts',
  'utils/object.ts',
  'utils/color.ts',
  'utils/module.ts',
  'utils/log.ts',
  'utils/figma.ts',
  'utils/figma-paint.ts',
  'utils/figma-style/gradient.ts',
  'utils/figma-style/style-resolver.ts',
  'utils/css.ts',
  'utils/tailwind.ts',
  'utils/tailwind-semantics.ts',
  'utils/codegen.ts',
  'utils/index.ts',
  'utils/tempad.ts',
  'composables/availability.ts',
  'composables/copy.ts',
  'composables/deep-link.ts',
  'codegen/worker.ts',
  'composables/input.ts',
  'composables/mcp.ts',
  'composables/plugin.ts',
  'composables/selection.ts',
  'composables/scrollbar.ts',
  'composables/toast.ts',
  'composables/index.ts',
  'plugin-sandbox/limits.ts',
  'plugin-sandbox/protocol.ts',
  'plugin-sandbox/validation.ts',
  'worker/safe.ts',
  'worker/lockdown.ts',
  'mcp/index.ts',
  'mcp/config.ts',
  'mcp/assets.ts',
  'mcp/bounded-response.ts',
  'mcp/local-styles.ts',
  'mcp/runtime.ts',
  'mcp/semantic-tree.ts',
  'mcp/bridge/content.ts',
  'mcp/broker/hub-client.ts',
  'mcp/broker/service-worker.ts',
  'mcp/broker/sessions.ts',
  'mcp/transform-variables/requester.ts',
  'mcp/transform-variables/worker.ts',
  'rewrite/config.ts',
  'rewrite/figma.ts',
  'rewrite/runtime.ts',
  'rewrite/shared.ts',
  'mcp/errors.ts',
  'mcp/encoding.ts',
  'mcp/tools/config.ts',
  'mcp/media.ts',
  'mcp/variable-references.ts',
  'mcp/tools/canvas/**/*.ts',
  'mcp/tools/design-system.ts',
  'mcp/tools/design-system-catalog.ts',
  'mcp/tools/structure.ts',
  'mcp/tools/screenshot.ts',
  'mcp/tools/code/layout-parent.ts',
  'mcp/tools/code/messages.ts',
  'mcp/tools/code/render/plugin.ts',
  'mcp/tools/code/render/props.ts',
  'mcp/tools/code/variables.ts',
  'mcp/tools/code/sanitize/negative-gap.ts',
  'mcp/tools/code/sanitize/relative-parent.ts',
  'mcp/tools/code/sanitize/stacking.ts',
  'mcp/tools/code/sanitize/index.ts',
  'mcp/tools/code/styles/layout.ts',
  'mcp/tools/code/styles/overflow.ts',
  'mcp/tools/code/styles/index.ts',
  'mcp/tools/code/assets/plan.ts',
  'mcp/tools/code/assets/vector.ts',
  'mcp/tools/code/budget-preflight.ts',
  'mcp/tools/code/assets/export.ts',
  'mcp/tools/code/assets/media.ts',
  'mcp/tools/code/assets/index.ts',
  'mcp/tools/code/styles/normalize.ts',
  'mcp/tools/code/styles/prepare.ts',
  'mcp/tools/code/tokens/extract.ts',
  'mcp/tools/code/tokens/index.ts',
  'mcp/tools/code/tokens/transform.ts',
  'mcp/tools/code/tokens/process.ts',
  'mcp/tools/code/tokens/rewrite.ts',
  'mcp/tools/code/tokens/source-index.ts',
  'mcp/tools/code/tokens/used.ts',
  'mcp/tools/code/text/types.ts',
  'mcp/tools/code/text/index.ts',
  'mcp/tools/code/text/segments.ts',
  'mcp/tools/code/text/style.ts',
  'mcp/tools/code/tokens/cache.ts',
  'mcp/tools/code/tokens/resolve.ts',
  'mcp/tools/token/candidates.ts',
  'mcp/tools/token/cache.ts',
  'mcp/tools/token/indexer.ts',
  'mcp/tools/token/mapping.ts',
  'mcp/tools/token/index.ts'
] as const
