export const TEMPAD_MCP_ERROR_CODES = {
  NO_ACTIVE_EXTENSION: 'NO_ACTIVE_EXTENSION',
  EXTENSION_TIMEOUT: 'EXTENSION_TIMEOUT',
  EXTENSION_DISCONNECTED: 'EXTENSION_DISCONNECTED',
  INVALID_SELECTION: 'INVALID_SELECTION',
  NODE_NOT_VISIBLE: 'NODE_NOT_VISIBLE',
  ASSET_SERVER_NOT_CONFIGURED: 'ASSET_SERVER_NOT_CONFIGURED',
  TRANSPORT_NOT_CONNECTED: 'TRANSPORT_NOT_CONNECTED'
} as const

export type TempadMcpErrorCode =
  (typeof TEMPAD_MCP_ERROR_CODES)[keyof typeof TEMPAD_MCP_ERROR_CODES]

export type TempadMcpErrorPayload = {
  code: TempadMcpErrorCode
  message: string
}
