import { z } from 'zod'

export const TEMPAD_MCP_ERROR_CODES = {
  NO_ACTIVE_EXTENSION: 'NO_ACTIVE_EXTENSION',
  EXTENSION_TIMEOUT: 'EXTENSION_TIMEOUT',
  EXTENSION_DISCONNECTED: 'EXTENSION_DISCONNECTED',
  INVALID_SELECTION: 'INVALID_SELECTION',
  NODE_NOT_VISIBLE: 'NODE_NOT_VISIBLE',
  CANVAS_READ_ONLY: 'CANVAS_READ_ONLY',
  CANVAS_UNSUPPORTED_EDITOR: 'CANVAS_UNSUPPORTED_EDITOR',
  CANVAS_BUSY: 'CANVAS_BUSY',
  INVALID_CANVAS_SCOPE: 'INVALID_CANVAS_SCOPE',
  INVALID_CANVAS_SPEC: 'INVALID_CANVAS_SPEC',
  CANVAS_APPLY_FAILED: 'CANVAS_APPLY_FAILED',
  ASSET_SERVER_NOT_CONFIGURED: 'ASSET_SERVER_NOT_CONFIGURED',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_HASH_MISMATCH: 'ASSET_HASH_MISMATCH',
  ASSET_TOO_LARGE: 'ASSET_TOO_LARGE',
  ASSET_MIME_UNSUPPORTED: 'ASSET_MIME_UNSUPPORTED',
  ASSET_BRIDGE_UNAVAILABLE: 'ASSET_BRIDGE_UNAVAILABLE',
  SVG_INVALID: 'SVG_INVALID',
  SVG_EXTERNAL_REFERENCE: 'SVG_EXTERNAL_REFERENCE',
  SVG_TOO_COMPLEX: 'SVG_TOO_COMPLEX',
  SVG_IMPORT_FAILED: 'SVG_IMPORT_FAILED',
  SVG_WRAPPER_DIRTY: 'SVG_WRAPPER_DIRTY',
  IMAGE_IMPORT_FAILED: 'IMAGE_IMPORT_FAILED',
  TRANSPORT_NOT_CONNECTED: 'TRANSPORT_NOT_CONNECTED'
} as const

export type TempadMcpErrorCode =
  (typeof TEMPAD_MCP_ERROR_CODES)[keyof typeof TEMPAD_MCP_ERROR_CODES]

export const TempadMcpErrorPayloadSchema = z
  .object({
    code: z.enum(TEMPAD_MCP_ERROR_CODES).optional(),
    message: z.string().min(1)
  })
  .strict()

export type TempadMcpErrorPayload = z.infer<typeof TempadMcpErrorPayloadSchema>
